kind: Service
apiVersion: v1
metadata:
  name: example2-bartender-service
spec:
  type: NodePort 
  selector:
    app: example2-bartender
  ports:
    - port:  7000
      targetPort: 7000
      nodePort: 30210
      protocol: TCP
